# Generated by Django 3.2.5 on 2022-05-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default='test', max_length=30),
            preserve_default=False,
        ),
    ]
